[tool.mypy]
strict = true
disallow_untyped_calls = false
exclude = ["scratch/.*"]


[[tool.mypy.overrides]]
module = ["datasets"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["colorama"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["setuptools"]
ignore_missing_imports = true

[tool.black]
line-length = 120

[dependency-groups]
dev = [
    "colorama>=0.4.6",
    "mypy>=1.19.1",
    "numpy>=2.4.0",
    "tensorboard>=2.20.0",
    "tensorflow>=2.20.0",
    "torch>=2.9.1",
]

